export interface Annuncio {
  id: string;
  titolo: string;
  descrizione: string;
  prezzo: number;
  provincia: string;
  comune: string;
  indirizzo: string;
  categoria: string;
  tipologia_immobile: string;
  tipo_contratto: 'IN VENDITA' | 'IN AFFITTO';
  stato: 'DISPONIBILE' | 'IN TRATTATIVA' | 'VENDUTO' | 'AFFITTATO';
  numero_locali: number;
  superficie_mq: number;
  piano: string | null;
  bagni: number;
  ape: string | null;
  ipe: number | null;
  riscaldamento: string | null;
  tipo_riscaldamento: string | null;
  sistema_radiante: string | null;
  cucina: string | null;
  box: string | null;
  giardino: boolean;
  terrazzo: boolean;
  ascensore: boolean;
  agenzia_nome: string | null;
  agenzia_indirizzo: string | null;
  agenzia_telefono: string | null;
  agenzia_email: string | null;
  immagine_url: string | null;
  created_at?: string;
}
